version: '3.7'

services:  #base image??
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lib
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup

  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/lib?useSSL=false&allowPublicKeyRetrieval=true
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.port=6379
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge