version: "3.7"

services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
    networks:
      - app
  db:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: mysql
    environment:
        MYSQL_DATABASE: lib
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/backup
    networks:
      - app
  lib:
    image: lib
    container_name: app_online
    ports:
      - '8082:8082'
    environment:
      - SERVER_PORT=8082
      - spring.datasource.url=jdbc:mysql://mysql:3306/lib
      - spring.redis.host=redis
      - spring.redis.port=6379
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db
    networks:
      - app
networks:
  app:




