version: '3.8'

services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lib
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup

  app:
    image: lib
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
      - localstack
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/lib?useSSL=false&allowPublicKeyRetrieval=true
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.port=6379
      - spring.datasource.username=root
      - spring.datasource.password=root
    restart: "no"
    networks:
      - shared-net

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-3
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

    networks:
        - shared-net

networks:
  shared-net:
    driver: bridge




